apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "homeboard.fullname" . }}-migrate-{{ .Release.Revision }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ default (printf "%s-tools" .Values.image.tag) .Values.image.toolsTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "dist/scripts/migrate.js"]
          env:
            - { name: DATABASE_URL, valueFrom: { secretKeyRef: { name: {{ .Values.secrets.existingSecret }}, key: {{ .Values.secrets.databaseUrlKey }} } } }
