apiVersion: v1
kind: Service
metadata: { name: {{ include "homeboard.fullname" . }} }
spec:
  selector: { app.kubernetes.io/name: {{ include "homeboard.name" . }} }
  ports: [{ port: {{ .Values.service.port }}, targetPort: http, name: http }]
