PRAGMA foreign_keys = ON;

-- SQLite uses TEXT for UUIDs, dates, timestamps, JSON arrays, and enum values.
-- CHECK constraints retain the PostgreSQL enum invariants without a separate type.
CREATE TABLE households (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))), name text NOT NULL, timezone text NOT NULL DEFAULT 'America/Chicago', fridge_pin_hash text, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP, subheading text NOT NULL DEFAULT 'Your people. Your little wins. Your home, together.', show_banner integer NOT NULL DEFAULT 1);
CREATE TABLE members (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), household_id text NOT NULL REFERENCES households(id) ON DELETE CASCADE, role text NOT NULL CHECK(role IN ('parent','child')), display_name text NOT NULL, email text, color text NOT NULL DEFAULT '#4F46E5', avatar_url text, password_hash text, active integer NOT NULL DEFAULT 1, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(household_id,email));
CREATE TABLE identities (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), member_id text NOT NULL REFERENCES members(id) ON DELETE CASCADE, provider text NOT NULL, subject text NOT NULL, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(provider,subject));
CREATE TABLE sessions (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), member_id text NOT NULL REFERENCES members(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, expires_at text NOT NULL, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE invitations (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), household_id text NOT NULL REFERENCES households(id) ON DELETE CASCADE, email text, token_hash text NOT NULL UNIQUE, expires_at text NOT NULL, consumed_at text, created_by text NOT NULL REFERENCES members(id), created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE display_devices (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), household_id text NOT NULL REFERENCES households(id) ON DELETE CASCADE, label text NOT NULL, token_hash text NOT NULL UNIQUE, last_seen_at text, revoked_at text, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE device_pair_codes (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), household_id text NOT NULL REFERENCES households(id) ON DELETE CASCADE, code_hash text NOT NULL UNIQUE, expires_at text NOT NULL, consumed_at text, created_by text NOT NULL REFERENCES members(id), created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE chore_groups (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), household_id text NOT NULL REFERENCES households(id) ON DELETE CASCADE, name text NOT NULL, assigned_member_id text REFERENCES members(id) ON DELETE SET NULL, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(household_id,name));
CREATE TABLE chore_templates (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), household_id text NOT NULL REFERENCES households(id) ON DELETE CASCADE, title text NOT NULL, instructions text, icon text, assignment_policy text NOT NULL DEFAULT 'individual' CHECK(assignment_policy IN ('individual','any','every')), approval_required integer NOT NULL DEFAULT 0, schedule_kind text NOT NULL CHECK(schedule_kind IN ('once','daily','weekdays','weekly')), start_date text NOT NULL, due_time text, weekdays text NOT NULL DEFAULT '[]', active integer NOT NULL DEFAULT 1, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP, chore_group_id text REFERENCES chore_groups(id) ON DELETE SET NULL, is_flexible integer NOT NULL DEFAULT 0);
CREATE TABLE chore_template_assignees (chore_template_id text NOT NULL REFERENCES chore_templates(id) ON DELETE CASCADE, member_id text NOT NULL REFERENCES members(id) ON DELETE CASCADE, PRIMARY KEY(chore_template_id,member_id));
CREATE TABLE chore_occurrences (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), chore_template_id text NOT NULL REFERENCES chore_templates(id) ON DELETE RESTRICT, household_id text NOT NULL REFERENCES households(id) ON DELETE CASCADE, scheduled_for text NOT NULL, due_at text, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(chore_template_id,scheduled_for));
CREATE TABLE chore_obligations (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), occurrence_id text NOT NULL REFERENCES chore_occurrences(id) ON DELETE CASCADE, member_id text REFERENCES members(id) ON DELETE SET NULL, status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','pending','completed','rejected','missed')), approval_status text NOT NULL DEFAULT 'not_required' CHECK(approval_status IN ('not_required','pending','approved','rejected')), completed_by text REFERENCES members(id) ON DELETE SET NULL, completed_at text, reviewed_by text REFERENCES members(id) ON DELETE SET NULL, reviewed_at text, rejection_note text, idempotency_key text UNIQUE, rescheduled_from_obligation_id text REFERENCES chore_obligations(id) ON DELETE RESTRICT, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE routine_templates (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), household_id text NOT NULL REFERENCES households(id) ON DELETE CASCADE, title text NOT NULL, icon text, assignment_policy text NOT NULL DEFAULT 'individual' CHECK(assignment_policy IN ('individual','any','every')), schedule_kind text NOT NULL CHECK(schedule_kind IN ('once','daily','weekdays','weekly')), start_date text NOT NULL, due_time text, weekdays text NOT NULL DEFAULT '[]', active integer NOT NULL DEFAULT 1, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE routine_template_assignees (routine_template_id text NOT NULL REFERENCES routine_templates(id) ON DELETE CASCADE, member_id text NOT NULL REFERENCES members(id) ON DELETE CASCADE, PRIMARY KEY(routine_template_id,member_id));
CREATE TABLE routine_steps (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), routine_template_id text NOT NULL REFERENCES routine_templates(id) ON DELETE CASCADE, position integer NOT NULL, title text NOT NULL, icon text, UNIQUE(routine_template_id,position));
CREATE TABLE routine_runs (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), routine_template_id text NOT NULL REFERENCES routine_templates(id) ON DELETE RESTRICT, household_id text NOT NULL REFERENCES households(id) ON DELETE CASCADE, scheduled_for text NOT NULL, member_id text REFERENCES members(id) ON DELETE SET NULL, completed_at text, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(routine_template_id,scheduled_for,member_id));
CREATE TABLE routine_step_completions (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), routine_run_id text NOT NULL REFERENCES routine_runs(id) ON DELETE CASCADE, routine_step_id text NOT NULL REFERENCES routine_steps(id) ON DELETE CASCADE, completed_by text REFERENCES members(id) ON DELETE SET NULL, completed_at text, UNIQUE(routine_run_id,routine_step_id));
CREATE TABLE audit_events (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), household_id text NOT NULL REFERENCES households(id) ON DELETE CASCADE, actor_id text REFERENCES members(id) ON DELETE SET NULL, action text NOT NULL, entity_type text NOT NULL, entity_id text, detail text NOT NULL DEFAULT '{}', created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE household_pin_attempts (household_id text PRIMARY KEY REFERENCES households(id) ON DELETE CASCADE, failed_attempts integer NOT NULL DEFAULT 0 CHECK(failed_attempts >= 0), last_failed_at text, locked_until text, updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE chore_group_rotations (id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))), household_id text NOT NULL REFERENCES households(id) ON DELETE CASCADE, first_group_id text NOT NULL REFERENCES chore_groups(id) ON DELETE CASCADE, second_group_id text NOT NULL REFERENCES chore_groups(id) ON DELETE CASCADE, first_member_id text NOT NULL REFERENCES members(id) ON DELETE CASCADE, second_member_id text NOT NULL REFERENCES members(id) ON DELETE CASCADE, start_date text NOT NULL, created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK(first_group_id <> second_group_id), CHECK(first_member_id <> second_member_id));
CREATE INDEX idx_occurrences_household_date ON chore_occurrences(household_id,scheduled_for);
CREATE INDEX idx_obligations_status ON chore_obligations(status);
CREATE UNIQUE INDEX idx_obligation_one_per_assignee ON chore_obligations(occurrence_id,COALESCE(member_id,''));
CREATE UNIQUE INDEX idx_routine_one_per_owner ON routine_runs(routine_template_id,scheduled_for,COALESCE(member_id,''));
CREATE UNIQUE INDEX idx_obligations_one_reschedule_per_source ON chore_obligations(rescheduled_from_obligation_id) WHERE rescheduled_from_obligation_id IS NOT NULL;
CREATE UNIQUE INDEX idx_chore_group_rotations_first_group ON chore_group_rotations(first_group_id);
CREATE UNIQUE INDEX idx_chore_group_rotations_second_group ON chore_group_rotations(second_group_id);
